### ISSUE TITLE
Use paragraphs for Florabank1 abstract

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#103]
The Florabank1 abstract is currently blocking the import of our DCAT feed, because it contains carriage returns. This should be solved in the next version of the IPT (https://github.com/gbif/ipt/issues/1231), but in the mean time, I have concatenated the abstract. Once the issue is solved, we should revert back to the old abstract (maybe also a good chance to review it), which might include multiple paragraphs.

We should test for:
- [ ] line breaks in a single paragraph text field
- [ ] the use of multiple paragraph text fields

Old abstract:

> Florabank1 is a database that contains distributional data on the wild flora indigenous species, archeophytes and naturalised aliens) of Flanders and the Brussels Capital Region. It holds about 3 million records of vascular plants, dating from 1800 till present. Furthermore, it includes ecological data on vascular plant species, redlist category information, Ellenberg values, legal status, global distribution, seed bank etc. The database is an initiative of "Flo.Wer" (http://www.plantenwerkgroep.be), the Research Institute for Nature and Forest (INBO) (http://www.inbo.be) and the National Botanic Garden of Belgium (http://www.br.fgov.be). Florabank aims at centralizing botanical distribution data gathered by both professional and amateur botanists and to make these data available to the benefit of nature conservation, policy and scientific research. The occurrence data contained in Florabank1 are extracted from checklists, literature and herbarium specimen information. Of survey lists, the locality name (verbatimLocality), species name, observation date and IFBL square code - the grid system used for plant mapping in Belgium (Van Rompaey 1943) - are recorded. For records dating from the period 1972–2004 all pertinent botanical journals dealing with Belgian flora were systematically screened. Analysis of herbarium specimens in the collection of the National Botanic Garden of Belgium, the University of Ghent and the University of Liège provided interesting distribution knowledge concerning rare species, this information is also included in Florabank1.
> 
> The data recorded before 1972 is available through the Belgian GBIF node (http://www.gbif.org/dataset/940821c0-3269-11df-855a-b8a03c50a862), not through Florabank1, to avoid duplication of information. A dedicated portal providing access to all currently published Belgian IFBL records is available at: http://projects.biodiversity.be/ifbl.
> 
> All data in Florabank1 is georeferenced. Every record holds the decimal centroid coordinates of the > IFBL square containing the observation. The uncertainty radius is the smallest circle possible covering the whole IFBL square, which can measure 1 km² or 4 km². Florabank is a work in progress and new occurrences are added as they become available; the dataset will be updated through GBIF on a regularly base.

**Comment by stijnvanhoey** [comment]
Two more resources were adapted to overcome the line breaks issue within string literals:
* Testwat
* Belgian Coccinellidae - Ladybird beetles in Belgium

These can be altered as well if the IPT issue is solved.

**Comment by peterdesmet** [comment]
https://github.com/gbif/ipt/issues/1231 is fixed. I have split the description of florabank1 back over 3 paragraphs, but this time in 3 separate fields rather than in one field. No further review/adaption was done. As this was not blocking the DCAT feed, I have not republished the dataset: this metadata update will be included in the next auto-publication.

@stijnvanhoey regarding TestWat and Coccinellidae: I don't know in what sections the original descriptions were split, so I have not updated those.

Closing issue.
