### ISSUE TITLE
Identical records in the Florabank except of their occurrenceID

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/data-publication#107]
It seems that Florabank contains records that are apparently identical, except they have different `occurrenceIDs`.

@andrejjh did run a query (on the latest publishedoccurrence.txt) that counts such records (identical scientificname, eventdate, recordedby,decimallatitude and decimallongitude fields) and found a lot of them, about 660.000 records!

One single occurrence appears with more than 2.000 occurrenceIDs:
`Teesdalia nudicaulis    2009-05-01    Simon Feys;Ward Vercruysse;Wouter Van Gompel    51.06661    2.57844`

If these records are truly independent occurrences, these should rather be published together with `individualCount` > 1, if this is possible.

This is how Andre produced [attached zipped csv file with duplicates](https://github.com/LifeWatchINBO/data-publication/files/157108/duplicates.csv.zip):
```
SELECT *
FROM (select scientificname, eventdate, recordedby, decimallatitude, decimallongitude, count(*) as count from occ 
GROUP BY scientificname, eventdate, recordedby,decimallatitude, decimallongitude 
ORDER BY count, scientificname) as tmp 
WHERE count > 1
```

**Comment by stijnvanhoey** [comment]
I could reproduce this error on the original dbase, using the following query:
```
SELECT *
FROM (SELECT 
		flora.scientificName
		, flora.eventDate
		, flora.recordedBy
		, flora.decimalLatitude
		, flora.decimalLongitude
		, COUNT(*) as counted
	  FROM [Flora_IPT].[ipt].[vwGBif] flora
	  GROUP BY flora.scientificName, flora.eventDate, flora.recordedBy,  flora.decimalLatitude, flora.decimalLongitude
	  ) AS tmp
WHERE counted > 1
ORDER BY tmp.counted, tmp.scientificName
```

Occurences are different entries for the `catalogNumber`, which origines from the `[METI_ID]` field in the `tblMeting`. @DimEvil do you know why these are considered?

**Comment by DimEvil** [comment]
@stijnvanhoey That is a legacy thing....
But, this is not the original database.... this is one of the first views we created for IPT.
What we decided, years ago, is that whenever it has a different occurrenceID, it's a different occurrence.
But...
I think we would need a look in the original Florabank to figure out what is actually happening. But it's not unthinkable that data was recorded multiple times, related to different projects.

In Florabank, it is not only the IFBL method (which is known to André) but also data from other projects was/is pumped in Florabank. Check: http://projects.biodiversity.be/ifbl for more info on the IFBL methodology

**Comment by stijnvanhoey** [comment]
@DimEvil What do you mean with legacy-thing? 

When I check this in the dbase, there is the table `tblWaarneming`, for which each *waarneming* is linked with different *metingen* from the table `tblMeting`. By combining these, the `occurenceID` were set up to make unique `IDs`. Take a look at the 4 most re-occuring records, were only the IDs (i.e. the ID in the `tblMeting`) are different:

| scientificName | eventDate |	recordedBy | decimalLatitude | decimalLongitude | counted |
|---------------------|---------------|------------------|----------------------|--------------------------|------------|
| Urtica dioica | 1996-06-01 | Jan Butaye | 51.00669 | 4.97453 |763 |
| Populus x canadensis | 1996-06-01 | Jan Butaye | 51.00669 | 4.97453 | 798 |
| Euphorbia paralias | 2008-08-01 | Simon Feys;Ward Vercruysse;Godfried Warreyn;Wouter Van Gompel | 51.09335 | 2.56313 | 867|
|Teesdalia nudicaulis | 2009-05-01 | Simon Feys;Ward Vercruysse;Wouter Van Gompel | 51.06661 | 2.57844 | 2007|

It seems rather strange that in this single  *Waarneming*, 2007 times the same *Meting* is registered? But I'm also wondering why this would be happening by the integration of data from multiple projects? The `tblProject` table is empty, so I can't check it in the view I'm working on...

**Comment by stijnvanhoey** [comment]
Apparently, part of the issue is the presence of a field METI_CMN_TAX, where information about the `opname` is included for a `waarneming`, leading to these type of descriptions in the METI_CMN_TAX field:
|               ...               |         ...            |
|----------------------------|-------------------|
|opnamenummer 112,| bedekking p1|
|opnamenummer 110,| bedekking p1|
|opnamenummer 108,| bedekking p1|
|opnamenummer 109,| bedekking p1|
|opnamenummer 114,| bedekking r1|
|               ...               |         ...            |

Something to discuss is if it is appropriate to convert these to individual occurrences in the DwC publication? @peterdesmet ?

**Comment by stijnvanhoey** [comment]
For keeping a log on the useful queries:
```
select * 
from dbo.tblMeting M 
where M.METI_WRNG_ID in 
(
select distinct tmp.meti_wrng_id from (
select count(*) as aantal
, M.METI_MEST_CDE
, M.METI_COR_X
, M.METI_COR_Y
, M.METI_TAXN_ID
, M.METI_WRNG_ID
from tblMeting M

group by M.METI_MEST_CDE
, M.METI_COR_X
, M.METI_COR_Y
, M.METI_TAXN_ID
, M.METI_WRNG_ID
having count(*) <> 1)tmp)
```

**Comment by stijnvanhoey** [comment]
After consultation of the data curator, the apparent duplicate records are actually different records. For example, for the `Teesdalia nudicaulis    2009-05-01    Simon Feys;Ward Vercruysse;Wouter Van Gompel    51.06661    2.57844` case, the records are all within the Carbour, as shown on the map:
![katjeskruid_carbour](https://cloud.githubusercontent.com/assets/754862/13599615/30749aac-e524-11e5-848c-f0365516219d.png)
(the code for the map creation is given in a [jupyter notebook](https://gist.github.com/stijnvanhoey/532dbb7ad92de1189474).

Due to the aggregation in grids, these appear to be duplicate observations. Keeping them with the original IDs in the dwc enables us to link back to the original database-record. Another solution would be to provide these original coordinates instead of the grid codes.

**Comment by DimEvil** [comment]
Most of the data is recorded in IFBL 1km 'streeplijst' format and there was an agreement to publish on IFBL km1 level. No further action needed this moment
