### ISSUE TITLE
niche-Vlaanderen Use of measurementsAndFacts possible?

### ISSUE THREAD

**Issue by DimEvil** [inbo/data-publication#116]
Instead of the GBIF relevee extension, we might like to try to get the releve data acceptable in the mesurementsAndFacts extension

**Comment by peterdesmet** [comment]
I'm not familiar with the differences between both. The advantage would be that we can actually publish the data, as the relevee extension is only available in sandbox mode? @kbraak, what do you think?

**Comment by DimEvil** [comment]
correct!

**Comment by kbraak** [comment]
The [Relevé extension](http://rs.gbif.org/sandbox/extension/releve_2016-02-26.xml) will move into production soon. 

Just a small reminder that GBIF does not currently index the [Measurement or Facts extension](http://rs.gbif.org/extension/dwc/measurements_or_facts.xml). GBIF has an [open issue ](http://dev.gbif.org/issues/browse/POR-3096) to implement this though. Please feel free to add your comments to the issue if you have any, thanks.

**Comment by DimEvil** [comment]
@kbraak 
Here: https://github.com/inbo/data-publication/tree/master/datasets/inboveg-niche-vlaanderen-events/DwC-A%20Niche is a DwC-A both including the releve extension and the Meas extension.

I think we did succeed in adding the whole releve section in measurements and facts. The only value which is imho not really good placed in the meas-extension is 'mossedIdentified'

any thoughts?

**Comment by kbraak** [comment]
Please note the Relevé extension has now been moved into production:

http://rs.gbif.org/extension/gbif/1.0/releve_2016-05-10.xml

**Comment by peterdesmet** [comment]
Thanks @kbraak. @DimEvil has republished InboVeg Niche Vlaanderen as v1.6 with the relevé extension and removed the measurementsOrFacts extension: http://data.inbo.be/ipt/resource?r=inboveg-niche-vlaanderen-events

If you want a version with the measurementsOrFacts, download the previous v1.5: http://data.inbo.be/ipt/resource?r=inboveg-niche-vlaanderen-events&v=1.5
