### ISSUE TITLE
DCAT feed Line breaks inside string literal of Depletion fishing in the rivers Grote Nete and Kleine Nete in Flanders, Belgium

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/data-publication#119]
The DCAT feed of the dataset is currently blocking the import of our DCAT feed, as line breaks are present inside a string literal:

```
dcat:keyword "Electric fishing
Red list
distribution mapping" , "Occurrence" , "Observation" ;
```

However, when checking the current keywords on the IPT: http://data.inbo.be/ipt/resource?r=depletion-fishing-nete-occurrences#keywords this line break does not seem to be represented in the resource. In contrast, when editing the keywords of the dataset: http://data.inbo.be/ipt/manage/metadata-keywords.do?r=depletion-fishing-nete-occurrences these seem to be different from the current version. @peterdesmet, should I update the version and recheck the resulting dcat-feed?

**Comment by peterdesmet** [comment]
Seems like the keywords were already comma-separated, but the resource was not republished. I'm having problems republishing... connection to source is slow.

**Comment by stijnvanhoey** [comment]
The remaining problem is the new line characters within string literals as discussed in #103 , closing things here.
