### ISSUE TITLE
Name server interim data should contain nameMatchValidation column

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#126]
Step 7, 8 and 9 as described in https://github.com/inbo/invasive-t0-occurrences/issues/52 should be done before writing to data/interim, so that [this file](https://github.com/inbo/data-publication/blob/4660346a54231e29dfabe1f3d9a6481dc1a7616d/datasets/name_server/data/interim/recorder_sql_unique_names_matched.csv) includes the `nameMatchValidation` column, which is useful for QA.

**Comment by stijnvanhoey** [comment]
add file [recorder_sql_unique_names_matched_annotated_verification.csv](https://github.com/inbo/data-publication/blob/master/datasets/name_server/data/interim/recorder_sql_unique_names_matched_annotated_verification.csv)  to provide the matchvalidation as well.
