### ISSUE TITLE
Reassess GBIF matching of name server

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#130]
We've completely reworked the GBIF name matching of name-server names. The T0 species are now filtered with the [aggregated-checklist](https://github.com/inbo/alien-species-checklist/blob/master/data/processed/aggregated-checklist.tsv). If we compare this with the original matching in [this old file](https://github.com/inbo/invasive-t0-occurrences/blob/791063e654a8fc934b19293b6e54c32bce2f55e2/data/vocabularies/species-list.tsv), there are a couple of differences:

## 6 keys were added

This caused by names previously not matching GBIF (fixed by the August update) or new acceptedKeys included in T0.

```
INBSYS0000005537: Cotoneaster integrifolius
INBSYS0000045069: Procambarus fallax	
NBNSYS0000003426: Cotoneaster integrifolius
NBNSYS0000142699: Baccharis halimifolia
NBNSYS0200002802: Parthenium hysterophorus
NHMSYS0000461158: Oenothera victorinii
```

### 5 keys have become an accepted names and are not included in T0

```
INBSYS0000003949	Sorbaria tomentosa	3012117
INBSYS0000005315	Erigeron annuus (L.) Desf. subsp. septentrionalis	4219549
INBSYS0000032668	Pueraria montana var. lobata	2977647
NBNSYS0000014018	Sorbaria tomentosa	3012117
NHMSYS0000463792	Sorbaria tomentosa	3012117
```

### 7 names no longer match GBIF

Maybe because we weren't using `strict` matching before:

```
NBNSYS0000004434	Aster x salignus
NBNSYS0000014614	Cotoneaster x suecicus 'Coral Beauty'
NBNSYS0000014763	Cotoneaster x suecicus 'Skogholm'
NBNSYS0000042601	Cotoneaster horizontalis agg.
NBNSYS0000188809	Sargassum muticum
NHMSYS0000460488	Lupinus polyphyllus agg.
NHMSYS0000463917	Spiraea salicifolia agg.
```

### 14 names that don't pass synonym matching

nbn_recommendedTaxonVersionKey | nbn_scientificName | gbifapi_usageKey | gbifapi_scientificName | gbifapi_status | gbifapi_acceptedKey | gbifapi_acceptedScientificName | nameMatchValidation
--- | --- | --- | --- | --- | --- | --- | ---
INBSYS0000033057 | Pueraria lobata | 2977654 | Pueraria lobata (Willd.) Ohwi | SYNONYM | 2977647 | Pueraria montana var. lobata (Willd.) Sanjappa... | ok: SYNONYM confirmed
INBSYS0000009681 | Oenothera depressa | 6428493 | Oenothera depressa Greene | SYNONYM | 6427623 | Oenothera villosa subsp. villosa | verify: SYNONYM probably invalid
NBNSYS0000014170 | Cotoneaster insculptus | 3025868 | Cotoneaster insculptus Diels | SYNONYM | 3026162 | Cotoneaster franchetii Boiss. | verify: SYNONYM probably invalid
NBNSYS0000033983 | Cotoneaster sternianus | 3026154 | Cotoneaster sternianus (Turrill) Boom | SYNONYM | 3026155 | Cotoneaster franchetii var. sternianus Turrill | verify: SYNONYM probably invalid
NBNSYS0000034267 | Cotoneaster atropurpureus | 3025910 | Cotoneaster atropurpureus K.E. Flinck & B. Hylmรถ | SYNONYM | 3025617 | Cotoneaster horizontalis Decne | verify: SYNONYM probably invalid
NBNSYS0100002637 | Cotoneaster vilmorinianus | 3025745 | Cotoneaster vilmorinianus G. Klotz | SYNONYM | 3025896 | Cotoneaster dielsianus E. Pritz. | verify: SYNONYM probably invalid
NHMSYS0000457554 | Cotoneaster amoenus | 8036392 | Cotoneaster amoena E. H Wilson | SYNONYM | 3026162 | Cotoneaster franchetii Boiss. | verify: SYNONYM probably invalid
NHMSYS0000457558 | Cotoneaster atropurpureus | 3025910 | Cotoneaster atropurpureus K.E. Flinck & B. Hylmรถ | SYNONYM | 3025617 | Cotoneaster horizontalis Decne | verify: SYNONYM probably invalid
NHMSYS0000457594 | Cotoneaster hummelii | 3025962 | Cotoneaster hummelii J. Fryer & B. Hylmรถ | SYNONYM | 3025565 | Cotoneaster acutifolius var. villosulus Rehd. ... | verify: SYNONYM probably invalid
NHMSYS0000457598 | Cotoneaster induratus | 3026187 | Cotoneaster induratus J. Fryer & B. Hylmรถ | SYNONYM | 3026162 | Cotoneaster franchetii Boiss. | verify: SYNONYM probably invalid
NHMSYS0000457622 | Cotoneaster pseudoambiguus | 3025789 | Cotoneaster pseudoambiguus J. Fryer & B. Hylmรถ | SYNONYM | 3025858 | Cotoneaster ambiguus Rehd. & E.H. Wilson | verify: SYNONYM probably invalid
NBNSYS0200002724 | Oenothera lipsiensis | 3664508 | Oenothera lipsiensis Rostanski & Gutte | SYNONYM | 7322773 | Oenothera deflexa Gates | verify: SYNONYM unresolved
NHMSYS0000457569 | Cotoneaster cinerascens | 3026204 | Cotoneaster cinerascens (Rehd.) Flinck & Hylmo | SYNONYM | 3026162 | Cotoneaster franchetii Boiss. | verify: SYNONYM unresolved
NHMSYS0000461156 | Oenothera rubricuspis | 3665801 | Oenothera rubricuspis Renner ex Rostanski | SYNONYM | 3188889 | Oenothera angustissima Gates | verify: SYNONYM unresolved

**Comment by peterdesmet** [comment]
`Pueraria montana` is on the T0 list, but `Pueraria montana var. lobata` (2977647) is not. That works fine for GBIF searches (which automatically searches for children), but an search in recorder will probably miss that variety + synonyms (according to GBIF) linking to it, such as `Pueraria lobata`.

@timadriaens Should we add `Pueraria montana var. lobata` to T0?

**Comment by timadriaens** [comment]
yes please, it's kudzu http://www.gbif.org/species/2977647

**Comment by peterdesmet** [comment]
Now added to recorder list: 19716c5951dc3dea507774939973ed30e78013e9.

It's hard to solve the 6 none-matches without manually altering names, so I'm closing this issue.
