### ISSUE TITLE
Create SAS event mapping SQL

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#135]

**Comment by peterdesmet** [comment]
@nicolasvanermen, do we want to include both primary and secondary observers in the published dataset? The primary has a direct connection to controlled vocabulary table, so it's easy to get the full name, but that is more difficult for the secondary observers, which are just (a comma separated list of) codes: `EA, MT`

**Comment by nicolasvanermen** [comment]
Eén waarnemer is voldoende voor mij. Zijn jullie begonnen met de datapaper?
