### ISSUE TITLE
Group description and additional information

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#136]
Dataset description and additional information are important fields for us: if a user reads anything, we want it to be that information. Luckily they appear both high on a GBIF dataset page (but not on the IPT). The additional information field however, does not support paragraphs, so this information is squished together (on IPT and GBIF). I would suggest to only use `description`, to keep this information always together and make use of the paragraphs to separate the different things we want to say, mainly:
1. General abstract (current description info)
2. Generalized and/or withheld information
3. Our usage norms paragraph.
4. Necessary funding information (e.g. for LifeWatch), rather than using Keywords or Project (where we would then only populate funding and have to invent a title)

I have started to this for a Natuurpunt dataset, and we have:

> Waarnemingen.be - Fish occurrences in Flanders and the Brussels Capital Region, Belgium is a species occurrence dataset published by Natuurpunt. The dataset contains close to 13,000 fish occurrences of 125 naturally occurring species (native, vagrant or migrant species), recorded by volunteers (citizen scientists), mainly since 2008. The occurrences are derived from the database http://www.waarnemingen.be, hosted at the nature conservation NGO Natuurpunt in collaboration with Stichting Natuurinformatie.
> 
> Generalized and/or withheld information: location information is generalized to 5 x 5 km² Universal Transverse Mercator (UTM) grid cells. Observer name, exact XY-coordinates, toponyms, and photographs are not included in the published dataset, but are known in the source database.
> 
> To allow anyone to use this dataset, we have released the data to the public domain under a Creative Commons Zero waiver (http://creativecommons.org/publicdomain/zero/1.0/). We would appreciate however, if you read and follow these norms for data use (http://www.natuurpunt.be/normen-voor-datagebruik [in Dutch]) and provide a link to the original dataset (http://doi.org/10.15468/7reil0) whenever possible. If you use these data for a scientific paper, please cite the dataset following the applicable citation norms and/or consider us for co-authorship. We are always interested to know how you have used or visualized the data, or to provide more information, so please contact us via the contact information provided in the metadata, natuurdata@natuurpunt.be or opendata@inbo.be.
> 
> The publication of this dataset was supported by the INBO as part of the Flemish contribution to LifeWatch.

Note, this might reintroduce #103, but that should be solved in https://github.com/gbif/ipt/issues/1231

@stijnvanhoey @DimEvil what do you think?

**Comment by stijnvanhoey** [comment]
I'm ok with this paragraph structure. What are the consequences for all the existing datasets?

**Comment by peterdesmet** [comment]
We'll have to update metadata in IPT + GitHub. I can do this.

**Comment by DimEvil** [comment]
Would it not be better to make this an issue for IPT further development?

**Comment by peterdesmet** [comment]
@DimEvil what would you suggest then for IPT development?

**Comment by peterdesmet** [comment]
This has now been updated for all datasets, but I did not republish.
