### ISSUE TITLE
Incorrect DOI for vis-estuarine-monitoring-events

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#141]
I accidentally republished [vis-estuarine-monitoring-events](http://data.inbo.be/ipt/resource?r=vis-estuarine-monitoring-events) under the same title as [vis-freshwater-monitoring-events](http://data.inbo.be/ipt/resource?r=vis-freshwater-monitoring-events) in [v1.4](http://data.inbo.be/ipt/resource?r=vis-estuarine-monitoring-events&v=1.4). This was corrected in v1.5 and another section updated in v1.6.

On GBIF however, this mistake caused the DOI of estuarine: http://doi.org/10.15468/jhv16z to be redirected to freshwater: http://www.gbif.org/dataset/b2906713-07c4-41b1-887f-adfc0a24b3ab I contacted Jan Legind to solve this.

I now notice the reverse is happening: the DOI of freshwater: http://doi.org/10.15468/klsy8u is redirected to estuarine.

**Comment by cgendreau** [comment]
now fixed

**Comment by peterdesmet** [comment]
Awesome, thanks @cgendreau 👏
