### ISSUE TITLE
Review dung beetles DwC mapping

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#147]
Here's my review of the DwC mapping of the Dung beetles dataset:

* [x] Dataset shortname: the code `DBWP` seems to be used, so I would opt for `dbwp-events` instead of `dwca-dung-beetles-of-the-western-palaearctic`

## Event Core

* [x] `eventID` are unique, but they have a non-ISO date and don't fit the pattern of locationID and occurrenceID: `B_KH_C1_Mon_26/09/2015`. I would maybe opt for: `INBO:DBWP:EVENT:number`, assuming that number can be included in the source dataset. Note that this field needs to be remapped in Event Core + Occurrence Extension
* [x] `eventDate`: are these supposed to include times? E.g. `2015-09-25T22:00:00Z`. I only encountered 22h and 23h. Format is correct ISO.
* [x] `year`, `month`, `day` does not correspond with eventDate. I would remove those three fields:
    * `2015-09-06 22:00:00 -> 2014 6   26`
    * `2014-12-07 23:00:00 -> 2014	8	12`
* [x] `locationID`: I would opt for the pattern `INBO:DBWP:LOC:number` instead of `DBWP:LOCIDnumber`
* [x] `countryCode`: required field by GBIF, would be good to add
* [x] `verbatimElevation`: these elevations are unambiguous and do not provide more info than `min/maxElevationInMeters`. Would remove the field
* [x] `coordinateUncertaintyInMeters`:  is it possible to make an educated guess?
* [x] `decimalLatitude/Longitude`: best to round to 5 decimals + have trailing zeros, e.g. `51.36000`

## Occurrence Extension

A lot of fields are repeated from the Event Core, which is harder to maintain and can cause discrepancies. I would remove the following fields:

* [x] type
* [x] datasetID
* [x] datasetName
* [x] samplingProtocol
* [x] sampleSizeValue
* [x] sampleSizeUnit
* [x] habitat
* [x] locationID
* [x] continent
* [x] country
* [x] locality
* [x] verbatimElevation
* [x] minimumElevationInMeters
* [x] maximumElevationInMeters

Also:

* [x] `occurrenceRemarks`: the bait is really samplingProtocol information, so I would join that info with samplingProtocol in the Event Core, to create:

```
pitfall (T1) with cattle dung bait
pitfall (T1) with goat dung bait
pitfall (T1) with horse dung bait
pitfall (T1) with red deer dung bait
pitfall (T1) with sheep dung bait
pitfall (T1L) with cattle dung bait
pitfall (T1L) with horse dung bait
pitfall (T1L) with sheep dung bait
pitfall (T5) with cattle dung bait
pitfall (T5) with goat dung bait
pitfall (T5) with horse dung bait
pitfall (T5) with red deer dung bait
pitfall (T5) with sheep dung bait
```

* [x] `occurrenceID`:  currently has the format `INBO:DBWP:ID1`. I would opt for `INBO:DBWP:OCC:number`
* [x] Would not populate `genus` and `specificEpithet`, but doesn't hurt either, as some taxa might be new?

Note: all the IDs I propose start with `INBO:`. If we should consider the dataset a `UGent` dataset (more correct?), than we should update those IDs as `UGent:` and the `institutionCode` should be `UGent` as well.

I did not review the metadata. Looks like a very cool dataset! 👍

**Comment by peterdesmet** [comment]
I also created a GitHub directory for this dataset (shortname to be confirmed) with specifications in whip: https://github.com/inbo/data-publication/tree/master/datasets/dbwp-occurrences

**Comment by milotictanja** [comment]
Something went wrong with the conversion of eventDates. This implies that the columns year, month and day were correct. In the new version of the dataset eventDates were corrected.

**Comment by DimEvil** [comment]
EventDate is now YYYY-MM-DD

**Comment by DimEvil** [comment]
Decimal latitudes and longitudes are in wrong format. (4.883.000 and 4.883.000) It looks like Access messed with the points and comma's again. (I ll fix)

**Comment by peterdesmet** [comment]
For documentation:

* eventID is of format `sourceSamplingEventID:date`: e.g. `BI_T5/41_T5:20140710`
* eventDate is of format `YYYY-MM-DD`
* locationID is of format `INBO:DBWP:LOC:7`
* occurrenceID is of format: `INBO:DBWP:OCC:51`

To do:

* [ ] Fix character encoding of import file, e.g. `locality` has `VÃƒÂ¡crÃƒÂ¡tÃƒÂ³t`. Was correct before.
* [ ] Coordinates currently only have 2 meaningful decimals, all the rest is 0. Should be something like `54.66666` instead of `54.66000`
* [ ] Remove `year`, `month`, `day`
* [ ] Leave `specificEpithet` empty for `Onthophagus sp.`, `Chilothorax sp.`, and `Aphodius sp.`
* [ ] Bodilopsis rufa (Moll, 1782) has different values in `genus`+ `specificEpithet`: `Agrilinus rufa` and `Bodilopsis rufa`. I assume first one is not correct?

And once published we should not forget to add DOI as `datasetID` (with `https://`)

**Comment by milotictanja** [comment]
Agrilinus rufus is an old synonym for Bodilopsis rufa, so this has been corrected to Bodilopsis rufa

**Comment by peterdesmet** [comment]
Moved dataset from http://data.inbo.be/ipt/resource?r=dung-beetles-of-the-western-palaearctic-events to http://data.inbo.be/ipt/resource?r=dbwp-events.

Process:

* [ ] Download dwca from old dataset
* [ ] Update every reference to shortname in eml.xml + update every version to 1.1
* [ ] Create new resource from dwca
* [ ] Remove source data files
* [ ] Use original source files
* [ ] Upload logo file again
* [ ] Publish
* [ ] Register (will warn about overwrite)
* [ ] Remove previous dataset via server (removing from IPT will trigger GBIF to remove it)

Meanwhile corrected:

* Remove `id` from data files (was added in the dwca)
* Fix character encoding issue in recordedBy (see e.g. https://www.gbif.org/occurrence/1586245948)
* Turn on automatic citation (will have correct URL and authors now)
* Add DOI to citation + in open data disclaimer
* Add Dimi and myself as authors (Dimi removed as additional party)
* Fix INBO name and address
* Fix typo in taxonomic coverage
* Add DOI URLs to citations
