### ISSUE TITLE
Suggestions invasive muntjak occurrences

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/data-publication#156]
I reviewed the csv exports in the invasive muntjak folder. 
Some suggestions to integrate and to make the data more the TrIAS-way:

1. Rearrange column names conform the order of the terms listed on the [GBIF DwC archive validator](https://tools.gbif.org/dwca-validator/extension.do?id=dwc:Event): (@DimEvil)

- type
- language
- license
- rightsHolder
- accessRights
- datasetID
- institutionCode
- datasetName
- ownerInstitutionCode (but see [this](https://github.com/inbo/data-publication/wiki/Data-guidelines-for-record-level-terms#ownerinstitutioncode)]
- dynamicProperties
- eventID
- parentEventID
- samplingProtocol
- eventDate
- locationID
- continent
- countryCode 
- verbatimLocality
- decimalLatitude
- decimalLongitude
- geodeticDatum
- verbatimLatitude
- verbatimLongitude
- verbatimCoordinateSystem
- verbatimSRS
- georeferenceSources

2. Complete README to [this style](https://github.com/trias-project/alien-plants-belgium/blob/master/README.md) (@myself)

3. We need to think about a datasetName (suggestion: Invasive muntjak occurrences in Flanders, Belgium). Now: `datasetName - Muntjak in Flanders, Belgium`

4. Clean folder and file(@myself):
- dwc_muntjak_events.csv --> events.csv
- dwc_muntjak_occurrences.csv --> occurrence.csv  
(cfr. [alien macroinvertebrate occurrences](https://github.com/trias-project/alien-macroinvertebrates/tree/master/data/processed/dwc_occurrence)
- remove capital letters from SQL files

**Comment by peterdesmet** [comment]
Regarding title:

To keep in line with previously published datasets:

    Invasive species - Chinese muntjac (Muntiacus reevesi) in Flanders, Belgium

Cf:

    Invasive species - American bullfrog (Lithobates catesbeianus) in Flanders, Belgium
    Invasive species - Chinese mitten crab (Eriocheir sinensis) in Flanders, Belgium
    Invasive species - Fallopia japonica on river dikes along the river Zeeschelde, Rupel and Durme

Alternatively we could use `Reeves's muntjac` in the title, but `Chinese muntjac` is more recognizable for Dutch speaking people

Shortname:

    invasive-muntjak-occurrences

**Comment by LienReyserhove** [comment]
@DimEvil could you change the datasetName from 
`datasetName - Muntjak in Flanders, Belgium`
to
`Invasive species - Chinese muntjac (Muntiacus reevesi) in Flanders, Belgium` please? 
Thanks!

**Comment by DimEvil** [comment]
Yes I could! It is changed now. It is changed in the Query is the field 'datasetName' and also in the IPT

**Comment by LienReyserhove** [comment]
Great, thanks!

**Comment by LienReyserhove** [comment]
All points were considered.
For point 2, we decided not to use the README for individual datasets.
Issue closed
