### ISSUE TITLE
Review of watervogels sampling-event dataset

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#169]
## event

- [x] `accessRights`: update to `https://www.inbo.be/en/norms-data-use`

- [X] `ownerInstitutionCode`: remove, see [here](https://github.com/inbo/data-publication/wiki/Data-guidelines-for-record-level-terms#ownerinstitutioncode)

- [X] `parentEventID`: the 2 IDs here `INBO:WATERVOGELS:EVENT:0000000001` and `INBO:WATERVOGELS:EVENT:0000000008` are not included in the data, remove this value

- [X] `samplingProtocol`: difference with previous values:
  - `survey on land` -> `Survey from land` I'm fine with the change, but should be lowercase at least 
  - `survey by boat` -> `Survey from boat` I'm fine with the change, but should be lowercase at least 

- [x] `samplingEffort`: 3 values (`all waterbirds counted`, `not all waterbirds counted` and empty), while previously there were 10 values and no empty:

```
all waterbirds counted	391999
all waterbirds except geese counted	5223
all waterbirds except gulls and geese counted	20606
all waterbirds except gulls and waders counted	89324
all waterbirds except gulls counted	156987
all waterbirds except waders, gulls, and geese counted	8719
only certain species counted	523
only swans and geese counted	3699
only waders counted	4178
specific species were not completely counted	186
```
- [x] `eventDate`: now goes back to 1966-12-14, previously only to 1991-10-13

- [x] `eventRemarks`: remove empty `{}` values (this error as also there in previous version)

- [x] `locationID`: 2,205 vs previously 1,203 unique values

- [x] `locationRemarks`: `cite centroid` this is a typo. Would suggest to use the field `georeferenceRemarks` instead with value `coordinates are centroid of location` cf previous and other datasets

- [x] `waterBody` instead of `verbatimLocality`: I think this change makes sense :+1:, but it deviates from other datasets.

- [x] `stateProvince` and `municipality` are removed, is this on purpose?

- [x] `decimalLatitude` and `decimalLongitude`: 9,071 records with empty values

## Occurrence

- [x] Don't add these fields to the query, they will be populated via the event core. Otherwise you have to maintain (and correct errors) in both.

```
          [type] = N'Event'
	, [language] = N'en'
	, [license] = N'http://creativecommons.org/publicdomain/zero/1.0/'
	, [rightsHolder] = N'INBO'
	, [accessRights] = N'https://github.com/LifeWatchINBO/norms-for-data-use'
	, [datasetID] = N'http://doi.org/10.15468/lj0udq'
	, [institutionCode] = N'INBO'
	, [datasetName] = N'Watervogels - Wintering waterbirds in Flanders, Belgium'
	, [ownerInstitutionCode] = N'INBO'
```

- [x] `occurrenceID`: currently of format `INBO:WATERVOGELS:Occ:0005253142`. For consistency, use `INBO:WATERVOGELS:OCC:0005253142`

- [x] `recordedBy`: contains `Onbekend`: either leave empty or use `unknown`
- [x] `recordedBy`: contains `INBO Instituut voor Natuur- en Bosonderzoek`. Would map to `INBO`
- [x] `recordedBy`: now contains full names, previously `L. Benoy` **only full name in warehouse**
- [x] `recordedBy`: now only contains first (?) observer, previously `L. Benoy | J. Van Ammel` **not available in warehouse**

- [x] `eventID`: refers to 111,182 unique values, while event core contains 115,640. Are the other 4,458 events zero-counts? **Yes**

- [x] `identifiedBy`: this field was dropped. Is it because it contains the same info as `recordedBy`? If so, fine to drop.

- [x] `taxonID`: prepend values with `euring:` cf. previous version of dataset: `euring:01860`

- [x] `scientificName`: is `-` for 3 taxonIDs. Best to verify those values!

```
99996	5     Chileense Taling
99997	14    Zilvertaling
99998	1    Andesgans
```

- [x] `taxonRank`: use lowercase `species` etc.

**Comment by DimEvil** [comment]
eventDate --> should be the interval now. Historic counts were not published

**Comment by DimEvil** [comment]
samplingEffort   --> all waterbirds counted  or not all waterbird counted (direct from DB)
eventRemarks    --> , [eventRemarks] = case CONCAT(IsgullsCounted,IsGeeseCounted,IsWaderCounted)
					WHEN '111' THEN 'waterbirds counted'
					WHEN '110' THEN 'waterbirds except waders counted'
					WHEN '001' THEN 'waterbirds except gulls and geese counted'
					WHEN '000' THEN 'waterbirds except waders, gulls and geese counted'
					WHEN '011' THEN 'waterbirds except gulls counted'
					WHEN '010' THEN 'waterbirds except gulls and waders counted'
					WHEN '101' THEN 'waterbirds except geese counted'
					WHEN '100' THEN 'waterbirds except geese and waders counted'
					ELSE 'unknown'
					END
dynamicProperties -->  {"samplingConditions":"favourable", "samplingCoverage":"complete", "snow":"none", "ice":"0%", "waterLevel":"normal"}

**Comment by DimEvil** [comment]
- [ ] `stateProvince` and `municipality` are removed, is this on purpose?  YES, now only regions in the DB which are not stateProvinces and/or municipalities

**Comment by peterdesmet** [comment]
Good to move json to dynamicProperties.

I wonder if samplingProtocol and eventRemarks cannot be joined. It's basically the same information, but more precise, no?

**Comment by DimEvil** [comment]
I hoped the same but it is not the case. See that I removed the word 'all' from the text, meaning that even when geese, waders and other were counted, this  does not means that all were counted

**Comment by peterdesmet** [comment]
Can you give a distinct list of both fields? I still think it is better to combine.

**Comment by DimEvil** [comment]
sampleProtocol and notsamplingEffort you mean. Ok that can be combimed.

**Comment by peterdesmet** [comment]
No, I meant combining `samplingEffort` with `eventRemarks` :-)

**Comment by DimEvil** [comment]
samplingEffort + eventRemarks is now:  _location completely counted & all waterbirds counted_

**Comment by DimEvil** [comment]
eventID: refers to 111,182 unique values, while event core contains 115,640. Are the other 4,458 events zero-counts?

Possibly, need to check
(Geteld, maar geen vogels) | Deze optie was beschikbaar in de vorige versie van de watervogelapplicatie, maar wordt niet langer aangeboden. Een nultelling registreer je nu door in het telformulier alle aantallen op 0 te laten staan en de telling op te slaan.

**Comment by DimEvil** [comment]
recordedBy: now only contains first (?) observer, previously L. Benoy | J. Van Ammel

Not avaiable in datawarehouse, we could get this info from the database if needed!

**Comment by DimEvil** [comment]
after update:
eventID: refers to 93349 unique values, while event core contains 94163. Are the other 4,458 events zero-counts?

--> 814 zero counts (this is possible)
