### ISSUE TITLE
Different occ count for VMM macroinvertebrates dataset

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#171]
The dataset on GBIF has the probably correct amount of 282,309 occurrences: https://www.gbif.org/dataset/5ca32e22-1f1b-4478-ba7f-1916c4e88d67

While the latest version on the IPT only shows 112 occurrences: https://ipt.inbo.be/resource?r=vmm-macroinvertebrates-events. There also don't seem to be any versions in the versions table.

**Comment by DimEvil** [comment]
I'll ask a new datadump from VMM
