### ISSUE TITLE
Whip vis-non-native-fish-occurrences 

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#174]
Many fields were missing from whip specs, I have added these

## Event

- [x] datasetName: update to `VIS - Non-native fish in Flanders, Belgium` (lowercase `fish`)
- [x] samplingProtocol: is this allowed to be empty?
- [x] samplingProtocol: almost always JSON, except for `depletionFishing`. Should it be left as such?
- [x] verbatimEventDate: this contains the exact same info as `eventDate`. Would drop field.
- [x] locationID: not always `visbestanden:\d{8}`, e.g. visbestanden:TL-BH4
- [ ] verbatimLocality: in MICA, Meetnetten we started using `locality`
- [ ] verbatimLat/Long: do you know the upper/lower limits for Flanders? I only have it for Belgium
- [x] verbatimCoordinateSystem: In older datasets we use `Belgian Lambert 72` (not `Belgium`), but in recent Saltabel and MICA we use the more correct[`Lambert coordinates`](https://github.com/inbo/data-publication/blob/master/datasets/saltabel-occurrences/specs/dwc_occurrence.yaml#L227). I suggest we stick to that.
- [x] verbatimSRS: `Belgian Datum 1972` not `Belgium Datum 1972`
- [x] coordinateUncertaintyInMeters: why is this 250?

## occurrence

- [x] recordedBy: are all fish captured by Hugo Verreycken?
- [x] occurrenceStatus: use lowercase `present`
- [ ] Misgurnus anguillicaudatus is missing taxonrank and authorship

**Comment by DimEvil** [comment]
locationID --> value in database
recordedBy --> is in VIS datasets de PI

occurrenceStatus --> is 'present' in query  'strange'

**Comment by DimEvil** [comment]
I will publish, only minor issues atm.
