### ISSUE TITLE
Not all saltabel records are in Belgium

### ISSUE THREAD

**Issue by peterdesmet** [inbo/data-publication#58]
_Note: this is an issue that was moved here from the deprecated saltabel-repository: https://github.com/LifeWatchINBO/saltabel-occurrences/issues/5_

1243 records found outside shapefile of Belgium. Some of these can be attributed to the coordinateUncertainty or the accuracy of the shapefile, but not all:

![saltabel belgium](https://f.cloud.github.com/assets/600993/2029729/930310ce-88ea-11e3-83e7-4a62b86eefd3.png)

Query:

```
SELECT s.cartodb_id, s.the_geom_webmercator, s.catalognumber 
FROM saltabel s, european_countries_export eu
WHERE eu.iso_2_code = 'BE'
AND NOT ST_Intersects(s.the_geom, eu.the_geom)
```

Answer from @DimEvil:

> Most of them are UTM 5 issues. For other occurrences out of Belgium, Tim
> has been contacted.

**Comment by DimEvil** [comment]
Could not find any outside Belgium on GBIF.  Also no issues on GBIF.
